steal("can/util",function(e){var t=function(e,r,o){o=o||{}
for(var a,s,u={foundObservable:!1},i=n(e,0,r,o,u),d=r.length,c=0;d>c;){s=i
for(var l=0,f=t.propertyReaders.length;f>l;l++){var v=t.propertyReaders[l]
if(v.test(i)){i=v.read(i,r[c],c,o,u)
break}}if(c+=1,i=n(i,c,r,o,u,s),a=typeof i,c<r.length&&(null===i||"function"!==a&&"object"!==a))return o.earlyExit&&o.earlyExit(s,c-1,i),{value:void 0,parent:s}}return void 0===i&&o.earlyExit&&o.earlyExit(s,c-1),{value:i,parent:s}},n=function(e,n,r,o,a,s){for(var u=0,i=t.valueReaders.length;i>u;u++)t.valueReaders[u].test(e,n,r,o)&&(e=t.valueReaders[u].read(e,n,r,o,a,s))
return e}
return t.valueReaders=[{name:"compute",test:function(e){return e&&e.isComputed},read:function(t,n,r,o,a){return o.isArgument&&n===r.length?t:(!a.foundObservable&&o.foundObservable&&(o.foundObservable(t,n),a.foundObservable=!0),t instanceof e.Compute?t.get():t())}},{name:"function",test:function(t,n,r,o){var a=typeof t
return!("function"!==a||t.isComputed||!(o.executeAnonymousFunctions||o.isArgument&&n===r.length)||e.Construct&&t.prototype instanceof e.Construct||e.route&&t===e.route)},read:function(t,n,r,o,a,s){return o.isArgument&&n===r.length?o.proxyMethods!==!1?e.proxy(t,s):t:t.call(s)}}],t.propertyReaders=[{name:"map",test:e.isMapLike,read:function(t,n,r,o,a){return!a.foundObservable&&o.foundObservable&&(o.foundObservable(t,r),a.foundObservable=!0),"function"==typeof t[n]&&t.constructor.prototype[n]===t[n]?o.returnObserveMethods?t[n]:"constructor"===n&&t instanceof e.Construct||t[n].prototype instanceof e.Construct?t[n]:t[n].apply(t,o.args||[]):t.attr(n)}},{name:"promise",test:function(t){return e.isPromise(t)},read:function(t,n,r,o,a){!a.foundObservable&&o.foundObservable&&(o.foundObservable(t,r),a.foundObservable=!0)
var s=t.__observeData
return t.__observeData||(s=t.__observeData={isPending:!0,state:"pending",isResolved:!1,isRejected:!1,value:void 0,reason:void 0},e.cid(s),e.simpleExtend(s,e.event),t.then(function(e){s.isPending=!1,s.isResolved=!0,s.value=e,s.state="resolved",s.dispatch("state",["resolved","pending"])},function(e){s.isPending=!1,s.isRejected=!0,s.reason=e,s.state="rejected",s.dispatch("state",["rejected","pending"])})),e.__reading(s,"state"),n in s?s[n]:t[n]}},{name:"object",test:function(){return!0},read:function(e,t){return null==e?void 0:e[t]}}],t.write=function(t,n,r,o){return o=o||{},e.isMapLike(t)?!o.isArgument&&t._data&&t._data[n]&&t._data[n].isComputed?t._data[n](r):t.attr(n,r):t[n]&&t[n].isComputed?t[n](r):void("object"==typeof t&&(t[n]=r))},t})